#pragma config(Sensor, in1,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           armMotor,      tmotorVex269, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program switches between multiple tasks by assis    	*|
|*              																							*|
|*                                                                                                    *|
*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 1     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 10    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 2     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 3     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 1     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down						*|
|*		Digital - Port 1		sonarSensor         Vex Sonic Sensor			Distance detector									*|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
#include "verk1.h"
#include "verk2.h"
#include "verk3.h"
#include "verk4.h"
#include "verk5.h"
#include "stopmotors.h"
task main()
{
	while(true)
		{
			if(vexRT[Btn7L] == 1)
				{
					beeptest();
				}

			if(vexRT[Btn8L] == 1)
			{
				stopmotors();
			}

			if(vexRT[Btn7R] == 1)
			{
				verk2();
			}

			if(vexRT[Btn7D] == 1)
			{
				verk3();
			}

			if(vexRt[Btn7U] == 1)
			{
				verk4();
			}

			if(vexRt[)
			{
			}


		}
}
